/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.ControladorLogin;
import javax.swing.JOptionPane;
import utilidades.Sesion;
/**
 *
 * @author dantj
 */
public class FrmLogin extends javax.swing.JFrame {
private ControladorLogin controlador = new ControladorLogin();
    
    public FrmLogin() {
     initComponents();
     setIconoVentana();
    setLocationRelativeTo(null); //Centra la ventana en la pantalla
    }

 /**
 * Asigna el logotipo institucional de CaféUTM a la barra de título de la ventana.
 */
private void setIconoVentana() {
    try {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuervo.png")).getImage());
    } catch (Exception e) {
        System.out.println("No se pudo cargar el icono de la ventana: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        plnDatosAcceso = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        pnlPasswordContenedor = new javax.swing.JPanel();
        txpPassword = new javax.swing.JPasswordField();
        lblVerPassword = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CaféUTM - Acceso al Sistema");

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(122, 15, 42));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CaféUTM");

        lblSubtitulo.setBackground(new java.awt.Color(204, 204, 204));
        lblSubtitulo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Universidad Tecnológica de Morelia");

        plnDatosAcceso.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresa tus datos de acceso"));

        lblUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        lblUsuario.setText("Matricula / Usuario:");
        lblUsuario.setIconTextGap(8);

        txtUsuario.setColumns(15);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N
        lblPassword.setText("Contraseña:");
        lblPassword.setIconTextGap(8);

        btnIngresar.setBackground(new java.awt.Color(122, 15, 42));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        pnlPasswordContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlPasswordContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        txpPassword.setColumns(15);
        txpPassword.setBorder(null);
        txpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpPasswordActionPerformed(evt);
            }
        });

        lblVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png"))); // NOI18N
        lblVerPassword.setToolTipText("Mostrar contraseña");
        lblVerPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlPasswordContenedorLayout = new javax.swing.GroupLayout(pnlPasswordContenedor);
        pnlPasswordContenedor.setLayout(pnlPasswordContenedorLayout);
        pnlPasswordContenedorLayout.setHorizontalGroup(
            pnlPasswordContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVerPassword)
                .addContainerGap())
        );
        pnlPasswordContenedorLayout.setVerticalGroup(
            pnlPasswordContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPasswordContenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txpPassword)
        );

        javax.swing.GroupLayout plnDatosAccesoLayout = new javax.swing.GroupLayout(plnDatosAcceso);
        plnDatosAcceso.setLayout(plnDatosAccesoLayout);
        plnDatosAccesoLayout.setHorizontalGroup(
            plnDatosAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsuario)
            .addGroup(plnDatosAccesoLayout.createSequentialGroup()
                .addGroup(plnDatosAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPasswordContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plnDatosAccesoLayout.setVerticalGroup(
            plnDatosAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnDatosAccesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPasswordContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CafeUTMLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(plnDatosAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plnDatosAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // Al presionar Enter en el campo usuario, se mueve el foco a la contraseña
        txpPassword.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpPasswordActionPerformed
        // TODO add your handling code here:
        btnIngresarActionPerformed(evt);
    }//GEN-LAST:event_txpPasswordActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    String usuario = txtUsuario.getText().trim();
String contrasena = String.valueOf(txpPassword.getPassword());

// Validaciones mínimas de captura antes de llamar al controlador[cite: 2]
if (usuario.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe capturar su matrícula o usuario.");
    txtUsuario.requestFocus();
    return;
}

if (contrasena.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe capturar su contraseña.");
    txpPassword.requestFocus();
    return;
}

// Se delega la validación de credenciales al controlador[cite: 2]
boolean acceso = controlador.iniciarSesion(usuario, contrasena);

if (acceso) {
    JOptionPane.showMessageDialog(this, "Bienvenido " + Sesion.getUsuario().getNombreUsuario()
            + "\nRol: " + Sesion.getUsuario().getRol().getNombreRol());

    // Se abre la ventana principal según el rol autenticado[cite: 2]
    FrmMenuPrincipal ventanaMenu = new FrmMenuPrincipal();
    ventanaMenu.setVisible(true);
    this.dispose(); // Se cierra la ventana de login[cite: 2]
} else {
    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos, o la cuenta se encuentra inactiva.",
            "Error de acceso", JOptionPane.ERROR_MESSAGE);
    txpPassword.setText("");
    txtUsuario.requestFocus();
}
    }//GEN-LAST:event_btnIngresarActionPerformed

    private boolean passwordVisible = false;
    
    private void lblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerPasswordMouseClicked
        // TODO add your handling code here:
       if (!passwordVisible) {
        // 1. Muestra la contraseña en texto plano
        txpPassword.setEchoChar((char) 0);
        passwordVisible = true;
        
        // 2. Cambia al icono de ojo cerrado / tachado
        try {
            lblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojocerrado.png")));
            lblVerPassword.setToolTipText("Ocultar contraseña");
        } catch (Exception e) {
            System.out.println("Error al cargar icono ojocerrado: " + e.getMessage());
        }
    } else {
        // 1. Vuelve a ocultar la contraseña con viñetas
        txpPassword.setEchoChar('•');
        passwordVisible = false;
        
        // 2. Restaura el icono de ojo abierto
        try {
            lblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojo.png")));
            lblVerPassword.setToolTipText("Mostrar contraseña");
        } catch (Exception e) {
            System.out.println("Error al cargar icono ojo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_lblVerPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVerPassword;
    private javax.swing.JPanel plnDatosAcceso;
    private javax.swing.JPanel pnlPasswordContenedor;
    private javax.swing.JPasswordField txpPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
