/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JOptionPane;
import modelo.Usuario;       
import utilidades.Sesion;    
import utilidades.DesktopFondo;
import utilidades.PanelFondo;
/**
 *
 * @author dantj
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
     /**
     * Creates new form FrmMenuPrincipal
     */
// Usuario actualmente autenticado (se obtiene de la clase Sesion)
private Usuario usuarioActivo;
   
    public FrmMenuPrincipal() {
       initComponents();
    this.usuarioActivo = Sesion.getUsuario();
    this.setExtendedState(MAXIMIZED_BOTH); // Maximiza la ventana al iniciar
    setIconoVentana();
    inicializarMenu();
    }
    
    private void inicializarMenu() {
    actualizarTitulo();
    aplicarPermisosPorRol();
}

private void actualizarTitulo() {
    this.setTitle("CaféUTM - Sistema de Gestión de Cafetería | Usuario: "
            + usuarioActivo.getNombreUsuario() + " | Rol: "
            + usuarioActivo.getRol().getNombreRol());
}

private void aplicarPermisosPorRol() {
    String rol = usuarioActivo.getRol().getNombreRol();

    // Por defecto, se desactivan las opciones administrativas
    itmMenuGestionUsuarios.setEnabled(false);
    itmMenuGestionProductos.setEnabled(false);
    opcMenuReportes.setEnabled(false);
    itmComandasCocina.setEnabled(false);

    if ("Administrador".equals(rol)) {
        // El Administrador tiene acceso total
        itmMenuGestionUsuarios.setEnabled(true);
        itmMenuGestionProductos.setEnabled(true);
        opcMenuReportes.setEnabled(true);
        itmComandasCocina.setEnabled(true);
    }
    // Alumno y Docente conservan activo únicamente el módulo de Pedidos
}

/**
 * Asigna el logotipo institucional de CaféUTM a la barra de título de la ventana.
 */
private void setIconoVentana() {
    try {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuervo.png")).getImage());
    } catch (Exception e) {
        System.out.println("No se pudo cargar el icono de la ventana: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        dskEscritorio = new utilidades.DesktopFondo()
        ;
        MenuBar = new javax.swing.JMenuBar();
        opcMenuUsuarios = new javax.swing.JMenu();
        itmMenuGestionUsuarios = new javax.swing.JMenuItem();
        opcMenuProductos = new javax.swing.JMenu();
        itmMenuGestionProductos = new javax.swing.JMenuItem();
        opcMenuPedidos = new javax.swing.JMenu();
        itmRealizarPedido = new javax.swing.JMenuItem();
        itmMisPedidos = new javax.swing.JMenuItem();
        itmComandasCocina = new javax.swing.JMenuItem();
        opcMenuReportes = new javax.swing.JMenu();
        itmMenuDemandaDiaria = new javax.swing.JMenuItem();
        opcMenuSalir = new javax.swing.JMenu();
        itmMenuCerrarSesion = new javax.swing.JMenuItem();
        itmMenuSalirSistema = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CaféUTM - Sistema de Gestión de Cafetería");

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        opcMenuUsuarios.setText("Usuarios");

        itmMenuGestionUsuarios.setText("Gestión de Usuarios");
        itmMenuGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMenuGestionUsuariosActionPerformed(evt);
            }
        });
        opcMenuUsuarios.add(itmMenuGestionUsuarios);

        MenuBar.add(opcMenuUsuarios);

        opcMenuProductos.setText("Productos");

        itmMenuGestionProductos.setText("Gestión de Productos");
        itmMenuGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMenuGestionProductosActionPerformed(evt);
            }
        });
        opcMenuProductos.add(itmMenuGestionProductos);

        MenuBar.add(opcMenuProductos);

        opcMenuPedidos.setText("Pedidos");

        itmRealizarPedido.setText("Realizar Pedido");
        itmRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRealizarPedidoActionPerformed(evt);
            }
        });
        opcMenuPedidos.add(itmRealizarPedido);

        itmMisPedidos.setText("Mis Pedidos");
        itmMisPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMisPedidosActionPerformed(evt);
            }
        });
        opcMenuPedidos.add(itmMisPedidos);

        itmComandasCocina.setText("Gestión de Comandas");
        itmComandasCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmComandasCocinaActionPerformed(evt);
            }
        });
        opcMenuPedidos.add(itmComandasCocina);

        MenuBar.add(opcMenuPedidos);

        opcMenuReportes.setText("Reportes");

        itmMenuDemandaDiaria.setText("Demanda Diaria");
        itmMenuDemandaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMenuDemandaDiariaActionPerformed(evt);
            }
        });
        opcMenuReportes.add(itmMenuDemandaDiaria);

        MenuBar.add(opcMenuReportes);

        opcMenuSalir.setText("Salir");

        itmMenuCerrarSesion.setText("Cerrar Sesión");
        itmMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMenuCerrarSesionActionPerformed(evt);
            }
        });
        opcMenuSalir.add(itmMenuCerrarSesion);

        itmMenuSalirSistema.setText("Salir del Sistema");
        itmMenuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMenuSalirSistemaActionPerformed(evt);
            }
        });
        opcMenuSalir.add(itmMenuSalirSistema);

        MenuBar.add(opcMenuSalir);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmMenuGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMenuGestionUsuariosActionPerformed
        // TODO add your handling code here:
 FrmGestionUsuarios frm = new FrmGestionUsuarios();
    
    // 1. Asigna el tamaño para que se vea toda la tabla y botones
    frm.setSize(890, 630);
    
    dskEscritorio.add(frm);
    
    // 2. Calcula la posición para centrarla en el escritorio
    int x = (dskEscritorio.getWidth() - frm.getWidth()) / 2;
    int y = (dskEscritorio.getHeight() - frm.getHeight()) / 2;
    frm.setLocation(x, y);
    
    frm.setVisible(true);
    }//GEN-LAST:event_itmMenuGestionUsuariosActionPerformed

    private void itmMenuGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMenuGestionProductosActionPerformed
        // TODO add your handling code here:
     FrmGestionProductos frm = new FrmGestionProductos();
    
    // Aumentamos la altura a 650 px para dar espacio a 'lblTotalProductos'
    frm.setSize(880, 650);
    
    dskEscritorio.add(frm);
    
    // Centra la ventana en el escritorio
    int x = (dskEscritorio.getWidth() - frm.getWidth()) / 2;
    int y = (dskEscritorio.getHeight() - frm.getHeight()) / 2;
    frm.setLocation(x, y);
    
    frm.setVisible(true);
    }//GEN-LAST:event_itmMenuGestionProductosActionPerformed

    private void itmComandasCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmComandasCocinaActionPerformed
        // TODO add your handling code here:
    FrmComandasCocina frm = new FrmComandasCocina();
    frm.setSize(920, 670);
    dskEscritorio.add(frm);
    frm.setLocation((dskEscritorio.getWidth() - frm.getWidth()) / 2, 
                    (dskEscritorio.getHeight() - frm.getHeight()) / 2);
    frm.setVisible(true);
    }//GEN-LAST:event_itmComandasCocinaActionPerformed

    private void itmMenuDemandaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMenuDemandaDiariaActionPerformed
        // TODO add your handling code here:
        FrmReportes frm = new FrmReportes();
         frm.setLocation((dskEscritorio.getWidth() - frm.getWidth()) / 2, 
                    (dskEscritorio.getHeight() - frm.getHeight()) / 2);
        dskEscritorio.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_itmMenuDemandaDiariaActionPerformed

    private void itmMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMenuCerrarSesionActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea cerrar sesión?",
        "Confirmar cierre de sesión",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

if (opcion == JOptionPane.YES_OPTION) {
    Sesion.cerrarSesion();
    FrmLogin frmLogin = new FrmLogin();
    frmLogin.setVisible(true);
    this.dispose();
}
    }//GEN-LAST:event_itmMenuCerrarSesionActionPerformed

    private void itmMenuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMenuSalirSistemaActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea salir del sistema?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);

if (opcion == JOptionPane.YES_OPTION) {
    System.exit(0);
}
    }//GEN-LAST:event_itmMenuSalirSistemaActionPerformed

    private void itmRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRealizarPedidoActionPerformed
        // TODO add your handling code here:
        FrmRealizarPedido frm = new FrmRealizarPedido();
    frm.setSize(960, 640);
    dskEscritorio.add(frm);
    frm.setLocation((dskEscritorio.getWidth() - frm.getWidth()) / 2, 
                    (dskEscritorio.getHeight() - frm.getHeight()) / 2);
    frm.setVisible(true);
    }//GEN-LAST:event_itmRealizarPedidoActionPerformed

    private void itmMisPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMisPedidosActionPerformed
        // TODO add your handling code here:
        FrmMisPedidos frm = new FrmMisPedidos();
    frm.setSize(980, 660);
    dskEscritorio.add(frm);
    frm.setLocation((dskEscritorio.getWidth() - frm.getWidth()) / 2, 
                    (dskEscritorio.getHeight() - frm.getHeight()) / 2);
    frm.setVisible(true);
    }//GEN-LAST:event_itmMisPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenuItem itmComandasCocina;
    private javax.swing.JMenuItem itmMenuCerrarSesion;
    private javax.swing.JMenuItem itmMenuDemandaDiaria;
    private javax.swing.JMenuItem itmMenuGestionProductos;
    private javax.swing.JMenuItem itmMenuGestionUsuarios;
    private javax.swing.JMenuItem itmMenuSalirSistema;
    private javax.swing.JMenuItem itmMisPedidos;
    private javax.swing.JMenuItem itmRealizarPedido;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu opcMenuPedidos;
    private javax.swing.JMenu opcMenuProductos;
    private javax.swing.JMenu opcMenuReportes;
    private javax.swing.JMenu opcMenuSalir;
    private javax.swing.JMenu opcMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
