/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import controlador.ControladorPedido; 
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dantj
 */
public class FrmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReportes
     */
    private ControladorPedido controlador = new ControladorPedido();
    public FrmReportes() {
       initComponents();
    cargarDemandaAcumulada();
    }

/**
     * Consulta la suma de cantidades pedidas (hoy y acumulado histórico)
     * y las muestra en tblDemanda con formato limpio y centrado.
     */
    private void cargarDemandaAcumulada() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; // Bloquear edición en celdas
            }
        };

        // 1. Definir los 4 encabezados
        modelo.addColumn("Producto");
        modelo.addColumn("Vendidos Hoy");
        modelo.addColumn("Total Histórico");
        modelo.addColumn("Recaudado ($)");
        tblDemanda.setModel(modelo);

        // 2. Llenar los datos desde el controlador
        List<Object[]> demanda = controlador.obtenerDemandaAcumulada();
        if (demanda != null) {
            for (Object[] fila : demanda) {
                String nombre = fila[0] != null ? fila[0].toString() : "N/A";

                // Limpiar el nombre si tiene paréntesis largos del paquete
                if (nombre.contains("(") && nombre.contains(")")) {
                    nombre = nombre.substring(0, nombre.indexOf("(")).trim();
                }

                int hoy = fila.length > 1 && fila[1] != null ? Integer.parseInt(fila[1].toString()) : 0;
                int totalHist = fila.length > 2 && fila[2] != null ? Integer.parseInt(fila[2].toString()) : 0;
                double recaudado = fila.length > 3 && fila[3] != null ? Double.parseDouble(fila[3].toString()) : 0.0;

                Object[] filaVisual = {
                    nombre,
                    hoy + " pzs",
                    totalHist + " pzs",
                    String.format("$%.2f", recaudado)
                };
                modelo.addRow(filaVisual);
            }
        }

        // 3. Estilos visuales y centrado de números
        tblDemanda.setRowHeight(30);
        tblDemanda.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tblDemanda.getTableHeader().setForeground(new java.awt.Color(122, 15, 42));

        if (tblDemanda.getColumnModel().getColumnCount() >= 4) {
            javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tblDemanda.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
            tblDemanda.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            tblDemanda.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReportes = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDemanda = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reportes - Demanda Diaria");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Vista de acumulación de demanda (unidades pedidas por producto)");

        tblDemanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Vendidos Hoy", "Total Histórico", "Recaudado ($)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDemanda);

        btnActualizar.setBackground(new java.awt.Color(122, 15, 42));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar Reporte");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarDemandaAcumulada();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblDemanda;
    // End of variables declaration//GEN-END:variables
}
